### ISSUE TITLE
Error: The katex preprocessor does not support the 'pdf' renderer

### ISSUE THREAD

**Issue by GopherJ** [HollowMan6/mdbook-pdf#27]

**Comment by HollowMan6** [comment]
Any details?

**Comment by HollowMan6** [comment]
See https://github.com/HollowMan6/mdbook-pdf?tab=readme-ov-file#common-issues
> 4. Failed to render my book for PDF in mdbook-pdf!
> 
> Will appreciate if you can report it to the [issue tracker](https://github.com/HollowMan6/mdbook-pdf/issues/new) providing all the traces for mdbook-pdf rendering as well as your book.toml. You can also provide the link to your book's repository if it's open source.

I would highly suspect this is related to the error in your book.toml configuration. Please read the README.md first! Close this issue for now unless you can confirm it's something related  to the software itself.

**Comment by Popaulol** [comment]
I am getting the same error but you can savely ignore it, atleast on my side it works fine with both katex and mdbook-pdf but you need to look out because sometimes parts of larger equation blocks get cut off on the sides.

**Comment by HollowMan6** [comment]
> but you need to look out because sometimes parts of larger equation blocks get cut off on the sides.

This is rather unfortunate, since the PDF is rendered by your browser, we can't do anything here on our code.

**Comment by Popaulol** [comment]
> > but you need to look out because sometimes parts of larger equation blocks get cut off on the sides.
> 
> This is rather unfortunate, since the PDF is rendered by your browser, we can't do anything here on our code.

Yeah i know, the comment was mostly mean to provide information to @GopherJ

Interestingly enough when i manually print the PDF using firefox, not chrome that doesn't appear but since firefox doesn't have an API that exposes printing easily that isn't really an option unless somebody wants to dig into the firefox codebase.

Also with Chrome and KaTeX you sometimes get images of scrollbars in the PDF (which looks as stupid as it sounds like) but manually printing to pdf through firefox also fixes that.

But since for the time being nothing can really be done about this, this isn't that big of a deal if you're careful with the size of your equations.

Just wanted to throw this info out there but don't really expect anything to be done about it since I don't think anyone here wants to dig into the chromium or firefox codebases. 
![image](https://github.com/HollowMan6/mdbook-pdf/assets/56090021/6949463a-4ce5-4209-a12c-0af17c7dcc31)
