### ISSUE TITLE
Don't use `mdbook-pdf-headless_chrome` fork

### ISSUE THREAD

**Issue by wulfgarpro** [HollowMan6/mdbook-pdf#37]
Hi, thanks for `mdbook-pdf`! 

Why was `rust-headless-chrome` replaced by `mdbook-pdf-headless_chrome` in 7250bba20eee89f79d5d5d4eea8050d6f4789a79?

I'd rather use the non-forked version of `rust-headless-chrome`. For now I'm patching `mdbook-pdf` at rev 9ea2011de98e30d6f3a04c6b8fe665e71fc29ada.

**Comment by HollowMan6** [comment]
It's because they haven't released the patches I submitted to the upstream:
- https://github.com/rust-headless-chrome/rust-headless-chrome/pull/442 for https://github.com/rust-headless-chrome/rust-headless-chrome/issues/441
- https://github.com/rust-headless-chrome/rust-headless-chrome/pull/439 for https://github.com/rust-headless-chrome/rust-headless-chrome/issues/436 and https://github.com/HollowMan6/mdbook-pdf/issues/31

Since you asked, join https://github.com/rust-headless-chrome/rust-headless-chrome/pull/442#issuecomment-1881736676 and ask to release a new version. I also don't want to spend time maintaining my own fork of `rust-headless-chrome`.

**Comment by wulfgarpro** [comment]
Thanks for the explanation.

How about, instead, you specify the git repo dependency until it's
released? See
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories
for me information.

**Comment by HollowMan6** [comment]
> It's because they haven't released the patches I submitted to the upstream. The only feasible way is to fork so that I can publish to crates.io:

> Thanks for the explanation. How about, instead, you specify the git repo dependency until it's released? See https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories for me information.

Then I can't publish mdbook-pdf to crates.io

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies

> Note: [crates.io](https://crates.io/) does not allow packages to be published with dependencies on code published outside of [crates.io](https://crates.io/) itself

**Comment by wulfgarpro** [comment]
Looks like a new version was released last week: https://github.com/rust-headless-chrome/rust-headless-chrome/releases/tag/v1.0.9.

**Comment by HollowMan6** [comment]
Now updated and released v0.1.8
