### ISSUE TITLE
PDF build failed 

### ISSUE THREAD

**Issue by ykla** [HollowMan6/mdbook-pdf#44]
My book in <https://github.com/taophilosophy/SEP-CN/>

book.toml：

```
[book]
authors = ["ykla"]
language = "zh"
multilingual = false
src = "src"
title = "test"
no-section-label = false
[output.html]

[output.pdf]
landscape = false
display-header-footer = true
print-background = true
theme = ""
scale = 0.8
paper-width = 8
paper-height = 10
margin-top = 0.5
margin-bottom = 0.5
margin-left = 0.5
margin-right = 0.5
page-ranges = ""
ignore-invalid-page-ranges = false
header-template = "<h3 style='font-size:8px; margin-left: 48%' class='title'></h3>"
footer-template = "<p style='font-size:10px; margin-left: 48%'><span class='pageNumber'></span> / <span class='totalPages'></span></p>"
prefer-css-page-size = true

[output.pdf-outline]
like-wkhtmltopdf = true
```

See also log file.
[result.log](https://github.com/HollowMan6/mdbook-pdf/files/14999328/result.log)

**Comment by HollowMan6** [comment]
Your book is insanely large ... I even can't load the page when I tried to open the `print.html` manually from Chrome (out of memory):

![image](https://github.com/HollowMan6/mdbook-pdf/assets/43995067/2db357ce-f780-40a4-a1fb-75cdb3ad7bc7)

![image](https://github.com/HollowMan6/mdbook-pdf/assets/43995067/1d61e2e5-1ee5-4abc-9f70-90bb1e415b20)

![image](https://github.com/HollowMan6/mdbook-pdf/assets/43995067/b42d0201-5188-491e-a570-5d12adbdd65e)

Also, by checking the logs, I can see there's nearly a 10 min gap without any event, so I would say either Chrome crashed because your computer runs out of memory or it's still waiting to get loaded. But if you believe your computer is having a very large memory and a OOM kill shouldn't happen, I will suggest you to extend the wait time with a larger value by adding the timeout field in your book.toml: https://github.com/HollowMan6/mdbook-pdf/blob/main/test_doc/book.toml#L13-L14
(Referring to https://github.com/HollowMan6/mdbook-pdf/issues/34#issuecomment-1854385791)

For solutions, I would suggest you to divide the book into smaller parts (I can see you already have those a,b,c,d,e...), and merge the PDFs if you feel like doing so (but anyway I don't think having a book with tens of thousands of pages is a good idea).
