### ISSUE TITLE
Only getting first page

### ISSUE THREAD

**Issue by Cliffback** [HollowMan6/mdbook-pdf#47]
Me again! Trying to make a pdf of a mdbook source, and everything compiles fine, but I only get the first page and no table of contents. This is the repo: [https://github.com/gbadev-org/tonc](https://github.com/gbadev-org/tonc)

It depends on mdbook-pandoc, mdbook-toc and mdbook-external-links.

A live server with the compiled book is up here for reference: [https://gbadev.net/tonc/](https://gbadev.net/tonc/)

Is it something wrong with my setup, or is the source perhaps not compatible with mdbook-pdf?

**Comment by HollowMan6** [comment]
Okay, thanks for letting me know the actual book behind the whole story! Now I understand why you said that the method I mentioned is not working https://github.com/HollowMan6/mdbook-pdf/issues/46#issuecomment-2080442343 They have customized commands for those preprocessors, which actually compile the dependencies checked out as submodules (they are not depending on the binaries you mentioned directly). The mdbook-pdf Docker image doesn't have the rust toolchain to compile those submodules. The book also depends on Python, which the Docker image doesn't have as well (All of these are to reduce the image size, and these compiling environments are not typically needed for books). Hence, I don't believe those commands really work https://github.com/HollowMan6/mdbook-pdf/issues/46#issuecomment-2079923365

To make life easier, let's not use Docker for this case. You need to have Rust toolchain https://rustup.rs/ and Python3 installed on your machine (enough for all mdbook-pdf related stuff, and also suggested here https://github.com/gbadev-org/tonc?tab=readme-ov-file#setup).

Execute the following commands:
```bash
# Install everything locally
cargo install --git https://github.com/HollowMan6/mdbook-pdf.git
cargo install --git https://github.com/HollowMan6/mdBook mdbook
python3 -m venv venv
source venv/bin/activate
pip3 install mdbook-pdf-outline

git clone https://github.com/gbadev-org/tonc
cd tonc
git submodule init
git submodule update --recursive
```

Add these lines to book.toml:
![image](https://github.com/HollowMan6/mdbook-pdf/assets/43995067/7b244c7a-db2e-4949-8e52-07dadde253ca)

Then, run `mdbook build` and you will find the outlined book at `output/pdf-outline/output.pdf`. I have attached a copy of what I have compiled:

[output.pdf](https://github.com/HollowMan6/mdbook-pdf/files/15139154/output.pdf)

I'll close this issue now since I don't find anything abnormal in the generated book above. Let me know if you have any other questions.

**Comment by HollowMan6** [comment]
I added the book you mentioned to the CI https://github.com/HollowMan6/mdbook-pdf/commit/63bd36097fc0b6e377b8653bc17b5535a3e4fb23 Now you can get the book from GitHub Actions Artifacts as well: https://github.com/HollowMan6/mdbook-pdf/actions/runs/8861938688 as well

**Comment by Cliffback** [comment]
Thank you so much, that is of such a huge help. The pdf you uploaded looks good, except some cropping issues, especially when it comes to the tables. On page 16 a lot of the text in the table is cropped out, while this is not the case when doing a normal print to pdf when viewing it in Chrome.

And thanks for adding it as an artifact :D

**Comment by HollowMan6** [comment]
> except some cropping issues, especially when it comes to the tables. On page 16 a lot of the text in the table is cropped out, while this is not the case when doing a normal print to pdf when viewing it in Chrome.

Theoretically, it should look the same, I guess you inherited some settings from your previous print when you printed that manually. You can always do so as well in mdbook-pdf. If text in the table is cropped out, I would suggest you fine-tune those margin settings https://github.com/HollowMan6/mdbook-pdf/blob/main/test_doc/book.toml#L31-L34, as well as the scale https://github.com/HollowMan6/mdbook-pdf/blob/main/test_doc/book.toml#L28


PS: Actually I found that the table on page 16 of the PDF generated from the CI looks good, so you might want to apply the same settings when you build your book locally https://github.com/HollowMan6/mdbook-pdf/blob/main/.github/workflows/test.yml#L228-L241 The PDF I generated out myself just use the default settings. 
[output.pdf](https://github.com/HollowMan6/mdbook-pdf/files/15145787/output.pdf)

**Comment by Cliffback** [comment]
I see the issue was only in the first one you linked to above, the issue went away in the build from artifacts and the one in the last comment, so all is good, thank you!

Regarding compiling, I might want to have to try on another machine, as I'm getting `error: failed to run custom build command for `headless_chrome v1.0.9`` when trying to install mdbook-pdf (that was why I initially went down the Docker route. I'm on arm64 macOS, not sure if it is some kind of incompatibility there

**Comment by HollowMan6** [comment]
> Regarding compiling, I might want to have to try on another machine, as I'm getting `error: failed to run custom build command for `headless_chrome v1.0.9`` when trying to install mdbook-pdf (that was why I initially went down the Docker route. I'm on arm64 macOS, not sure if it is some kind of incompatibility there

It should be fine with builds on MacOS as the build CI passed. Anyway you can always get the binary from the CI or release: [mdbook-pdf-v0.1.8-aarch64-apple-darwin](https://github.com/HollowMan6/mdbook-pdf/releases/download/v0.1.8/mdbook-pdf-v0.1.8-aarch64-apple-darwin)

**Comment by Cliffback** [comment]
Thanks, the binary did the trick!
