### ISSUE TITLE
Headless_chrome doesn't stop

### ISSUE THREAD

**Issue by samuelenegrato** [HollowMan6/mdbook-pdf#48]
Hi,

I'm creating many documents based on mdbook-pdf and I've noticed that during the build phase, some processes "chrome.exe" are not being properly terminated. This is causing a reduction in machine performance, with CPU usage maxing out.

Browser used: Chrome
Version: 124.0.6367.119 (64-bit)"

**Comment by HollowMan6** [comment]
Hi, did all your builds complete successfully with no error message? This is more likely to be caused by [rust-headless-chrome](https://github.com/rust-headless-chrome/rust-headless-chrome) and I guess we can't do much on our side. I would suggest you open an issue there as well and see if they have similar situations / can fix.

**Comment by samuelenegrato** [comment]
No, it doesn't generate any kind of error for me, but the build phase slows down significantly. As suggested by you, I opened an issue. [#482](https://github.com/rust-headless-chrome/rust-headless-chrome/issues/482)

**Comment by samuelenegrato** [comment]
Updating the version resolved the problem
